/*
 * error.h
 *
 *  Created on: Sep 24, 2014
 *      Author: patrick
 */

#ifndef ERROR_H_
#define ERROR_H_

#define INSUFFICIENT_FUNDS 0x5

#define CREATE_ACCOUNT_FAILURE 0X1
#define CREATE_ACCOUNT_FAILURE_INVALID_USER 0X2
#define CREATE_ACCOUNT_FAILURE_EXISTS 0X4

#define DELETE_ACCOUNT_FAILURE 0X4
#define INVALID_ACCOUNT_ID 0X8
#define WITHDRAW_ERROR 0X1
#define DEPOSIT_ERROR 0X1

#define SQL_INSERT_FAILED 0x1
#define SQL_SELECT_FAILED 0X2
#define SQL_QUERY_FAILED 0X2

#define INVALID_PARAMERTIZED_QUERY 0X1

#define SQL_SUCCESS 0

#define USER_PERMISSION_USER 0X0
#define USER_PERMISSION_MAINTENANCE 0X1
#define USER_PERMISSION_ADMIN 0X2

#define AUTHENTICATION_FAILURE 0x1
#define CREATE_USER_FAILURE 0x1
#define CREATE_USER_FAILURE_USER_EXISTS 0x2
#define DELETE_USER_FAILURE 0x1


#define USER_NOT_EXIST 0X5

#define AUTHENTICATION_FAILURE 0x1
#define AUTHENTICATION_SUCCESS 0x0


#endif /* ERROR_H_ */
