/*
 * error.h
 *
 *  Created on: Sep 24, 2014
 *      Author: patrick
 */

#ifndef ERROR_H_
#define ERROR_H_

#define INSUFFICIENT_FUNDS 0x1

#define CREATE_ACCOUNT_FAILURE 0X2
#define CREATE_ACCOUNT_FAILURE_INVALID_USER 0X3
#define CREATE_ACCOUNT_FAILURE_EXISTS 0X4

#define DELETE_ACCOUNT_FAILURE 0X5
#define INVALID_ACCOUNT_ID 0X6
#define WITHDRAW_ERROR 0X7
#define DEPOSIT_ERROR 0X8

#define SQL_INSERT_FAILED 0x9
#define SQL_SELECT_FAILED 0X10
#define SQL_QUERY_FAILED 0X11

#define INVALID_PARAMERTIZED_QUERY 0X12

#define SQL_SUCCESS 0

#define CREATE_USER_FAILURE 0x17
#define CREATE_USER_FAILURE_USER_EXISTS 0x18
#define DELETE_USER_FAILURE 0x19

#define USER_NOT_EXIST 0X20

#define AUTHENTICATION_FAILURE 0x21
#define AUTHENTICATION_SUCCESS 0x22

#define ACCOUNT_NOT_EXIST 0X23

#define MAKE_PURCHASE_FAILURE 0x24

#define YEAR_OUT_OF_RANGE 0x25
#define MONTH_OUT_OF_RANGE 0x26
#define FREEZE_ERROR 0x27

#endif /* ERROR_H_ */
